### ISSUE TITLE
Unable to get video preview for videos stored on Firebase storeage

### ISSUE THREAD

**Issue by Wizpna** [TheAlphamerc/flutter_plugin_add_thumbnail#1]
Thanks for the awesome plugin,

I tried using the plugin to get a video preview for videos stored on firebase storage but I was unable.

Your help will be highly needed.

**Comment by TheAlphamerc** [comment]
@Wizpna Can you share the video URL link which you are using?

**Comment by Wizpna** [comment]
This is the video url: https://firebasestorage.googleapis.com/v0/b/mhagic-a1145.appspot.com/o/video%2F2-9-2020%2F6-5-27-348%2FnTlvFKJS9HO1qEncIkEgTgVzjMq2?alt=media&token=afbdf5b0-c5ce-483c-b3ab-48d51d85bed9

**Comment by TheAlphamerc** [comment]
@Wizpna add_thumbnail package generally get a video thumbnail URL from the HTML content of the website instead of getting a video thumbnail from video. For example in Youtube website when you open a video its thumbnail with other information remain available in its HTML content and the package collect this information and displayed thumbnail and title.

**Comment by Wizpna** [comment]
Thanks for the timely response, i will close this issue for now because i have been able to achieve what i wanted to do.

Thanks once more.

**Comment by oGranny** [comment]
Hi @Wizpna, 
i am also building something similar, can you please tell how did you get the thumbnail of video you stored on firebase

**Comment by Wizpna** [comment]
I wrote my own logic to achieve that.

I did not use this plugin.

**Comment by oGranny** [comment]
Thanks for replying @Wizpna, 
Can you share the code please I don't have much experience with videos in flutter and don't know much about them it would be great if you can help me.
Thanks
